### ISSUE TITLE
Error LeakyReLU.cu:29

### ISSUE THREAD

**Issue by xuyingzhongguo** [yinglinzheng/FTCN#10]
I ran 
```
python test_on_raw_video.py examples/shining.mp4 output
```
It returned me this error. Anyone has idea why this happened?
Thanks!
```
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/THCUNN/generic/LeakyReLU.cu line=29 error=209 : no kernel image is available for execution on the device
Traceback (most recent call last):
  File "test_on_raw_video.py", line 50, in <module>
    input_file, return_frames=True, max_size=max_frame
  File "/data/test_tools/common.py", line 85, in detect_all
    [detector.detect(item) for item in partition(frames, 50)]
  File "/data/test_tools/common.py", line 85, in <listcomp>
    [detector.detect(item) for item in partition(frames, 50)]
  File "/data/test_tools/ct/detection/detector.py", line 36, in detect
    return batch_detect(self.model, np.array(images), self.device)
  File "/data/test_tools/ct/detection/alignment.py", line 567, in batch_detect
    loc, conf, landms = net(img)  # forward pass
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/test_tools/ct/detection/alignment.py", line 253, in forward
    out = self.body(inputs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torchvision/models/_utils.py", line 63, in forward
    x = module(x)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/activation.py", line 559, in forward
    return F.leaky_relu(input, self.negative_slope, self.inplace)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/functional.py", line 1061, in leaky_relu
    result = torch._C._nn.leaky_relu_(input, negative_slope)
RuntimeError: cuda runtime error (209) : no kernel image is available for execution on the device at /opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/THCUNN/generic/LeakyReLU.cu:29
```

**Comment by xuyingzhongguo** [comment]
Packages:
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
albumentations            1.3.0                    pypi_0    pypi
blas                      1.0                         mkl  
ca-certificates           2023.01.10           h06a4308_0  
certifi                   2022.12.7        py38h06a4308_0  
contexttimer              0.3.3                    pypi_0    pypi
contourpy                 1.0.7                    pypi_0    pypi
cudatoolkit               10.1.243             h6bb024c_0 
cycler                    0.11.0                   pypi_0    pypi
einops                    0.6.0                    pypi_0    pypi
ffmpeg-python             0.2.0                    pypi_0    pypi
filterpy                  1.4.5                    pypi_0    pypi
fonttools                 4.38.0                   pypi_0    pypi
freetype                  2.12.1               h4a9f257_0  
future                    0.18.3                   pypi_0    pypi
fvcore                    0.1.5.post20221221          pypi_0    pypi
giflib                    5.2.1                h5eee18b_3  
imageio                   2.9.0                    pypi_0    pypi
imgaug                    0.4.0                    pypi_0    pypi
importlib-resources       5.12.0                   pypi_0    pypi
intel-openmp              2021.4.0          h06a4308_3561  
iopath                    0.1.10                   pypi_0    pypi
joblib                    1.2.0                    pypi_0    pypi
jpeg                      9e                   h7f8727e_0  
kiwisolver                1.4.4                    pypi_0    pypi
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.38                 h1181459_1  
lerc                      3.0                  h295c915_0  
libdeflate                1.8                  h7f8727e_5  
libffi                    3.4.2                h6a678d5_6  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              11.2.0               h1234567_1  
libtiff                   4.5.0                h6a678d5_1  
libwebp                   1.2.4                h11a3e52_1  
libwebp-base              1.2.4                h5eee18b_1  
lmdb                      1.4.0                    pypi_0    pypi
lz4-c                     1.9.4                h6a678d5_0  
matplotlib                3.7.0                    pypi_0    pypi
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py38h7f8727e_0  
mkl_fft                   1.3.1            py38hd3c417c_0  
mkl_random                1.2.2            py38h51133e4_0  
ncurses                   6.4                  h6a678d5_0  
networkx                  3.0                      pypi_0    pypi
ninja                     1.10.2               h06a4308_5  
ninja-base                1.10.2               hd09550d_5  
numpy                     1.23.5           py38h14f4228_0  
numpy-base                1.23.5           py38h31eccc5_0  
opencv-python             4.7.0.68                 pypi_0    pypi
opencv-python-headless    4.7.0.68                 pypi_0    pypi
opencv-transforms         0.0.6                    pypi_0    pypi
openssl                   1.1.1t               h7f8727e_0  
packaging                 23.0                     pypi_0    pypi
pandas                    1.5.3                    pypi_0    pypi
pickle5                   0.0.11                   pypi_0    pypi
pillow                    7.1.0                    pypi_0    pypi
pip                       22.3.1           py38h06a4308_0  
portalocker               2.7.0                    pypi_0    pypi
prettytable               3.6.0                    pypi_0    pypi
protobuf                  3.20.3                   pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
python                    3.8.16               h7a1cb2a_2  
python-dateutil           2.8.2                    pypi_0    pypi
pytorch                   1.4.0           py3.8_cuda10.1.243_cudnn7.6.3_0    pytorch
pyturbojpeg               1.7.0                    pypi_0    pypi
pytz                      2022.7.1                 pypi_0    pypi
pywavelets                1.4.1                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
qudida                    0.0.4                    pypi_0    pypi
readline                  8.2                  h5eee18b_0  
scikit-image              0.16.2                   pypi_0    pypi
scikit-learn              1.2.1                    pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
setuptools                65.6.3           py38h06a4308_0  
shapely                   2.0.1                    pypi_0    pypi
simplejson                3.18.3                   pypi_0    pypi
six                       1.16.0             pyhd3eb1b0_1  
sklearn                   0.0.post1                pypi_0    pypi
sqlite                    3.40.1               h5082296_0  
tabulate                  0.9.0                    pypi_0    pypi
tensorboardx              2.6                      pypi_0    pypi
termcolor                 2.2.0                    pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
torchvision               0.5.0                py38_cu101    pytorch
typing-extensions         4.5.0                    pypi_0    pypi
wcwidth                   0.2.6                    pypi_0    pypi
wheel                     0.38.4           py38h06a4308_0  
xz                        5.2.10               h5eee18b_1  
yacs                      0.1.8                    pypi_0    pypi
zipp                      3.14.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0  
zstd                      1.5.2                ha4553b6_0  
```

**Comment by hellogeraldblah** [comment]
hi, i am also having this issue.. did you manage to fix it? and if so, how?
